# 2021-11-08
# This script takes the sequence table generated by the find_SNVs.R script and detects sequences with indels

library(tidyverse)

# Arguments:
# datapath is the path to the sequence table from the find_SNVs.R script
# outdir is the place where the indel data should be written to
# PBS is the sequence of the pegRNA PBS
# RTT is the sequence of the pegRNA RTT
# Example: find_indels("/path/to/sequences/45-1-4-target_sequences.tsv", "/output/path", "CAGACTGAGCACG", "TGATGGCAGAGGAAAGGAAGCCCTGCTTCCTCCA|TGATGGCAAAGGAAAGGAAGCCCTGCTTCCTCCA"

find_indels <- function(datapath, outdir, PBS, RTT) {
  x <- read_tsv(datapath)
  filename = str_remove(basename(datapath), "-target_sequences.tsv")
  indel_table <- mutate(x, sequence_ins_context = paste0("CCGAGCAGAAGAA", sequence_trim, "GAAGGGCTCCCATCACATCAACCGGTGGCGCATT"),
      trim_lib = ifelse(sequence_ins_context %in% toupper(paste0("CCGAGCAGAAGAA", library_annotation$sequence_original, "GAAGGGCTCCCATCACATCAACCGGTGGCGCATT")), T, F)) %>%
    filter(trim_lib == F) %>%
    mutate(preserved_target = str_detect(sequence, preserved)) %>%
    filter(preserved_target == F & !str_detect(sequence, "N")) %>%
    filter(length != 120)
  write_tsv(indel_table, paste0(outdir, filename, "_indel_sequences.tsv"))
  indel_count <- sum(indel_table$count)/sum(x$count)*100
  write_tsv(tibble("percIndel" = indel_count, "sample" = filename), paste0(outdir, filename, "_indel_counts.tsv"))
}